env:
  global:
    - CC_TEST_REPORTER_ID=64d1468e17f8994daaac252fab3e9eacc7fc6c58366069a32473d21d2d684f24
language: node_js
node_js:
  - "8"
  - "10"
os:
  - linux
  - os: osx
    osx_image: xcode9.4
cache:
  directories:
  - node_modules # NPM packages
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install clang-format;
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install clang-format;
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter;
    else
      echo Error:TRAVIS_OS_NAME && exit 1;
    fi
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - clang-format --version
  - npm run build
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    on_success: never
    on_failure: change
